CFLAGS = -O2

SRCS = aprstlm.c connect_client.c decode_tlm_pkt.c detect_tlm_pkt.c generic_clkqth.c generic_display.c generic_keyboard.c generic_static.c ncurses_setup.c

all:		$(SRCS)
		gcc  $(CFLAGS) -c $(SRCS) 
